#!/bin/sh
set -e
if [ "$1" = configure ]; then
    glib-compile-schemas /usr/share/glib-2.0/schemas
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t /usr/share/icons/hicolor || true
    fi
fi
