#!/bin/sh
set -e
case "$1" in
    remove|purge)
        if command -v glib-compile-schemas >/dev/null 2>&1; then
            glib-compile-schemas /usr/share/glib-2.0/schemas
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -q -t /usr/share/icons/hicolor || true
        fi
        ;;
esac
